/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenkafshetgaruese;


import java.awt.event.WindowEvent;
import java.util.Enumeration;
import java.util.Random;
import java.util.Vector;

/**
 *
 * @author fitor
 */
public class MainForm extends javax.swing.JFrame implements Garon{
    public int distanca1=0;
    public int distanca2=0;
    public int distanca3=0;
    public int distanca4=0;
    
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 210, 210));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, 71, 28));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 449, 71, 26));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 201, 71, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 325, 71, 28));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 163, 37, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 232, 256, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\fitor\\OneDrive\\Documents\\NetBeansProjects\\mavenKafshetGaruese\\src\\main\\java\\com\\mycompany\\mavenkafshetgaruese\\race.png")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     @Override
    public void vrapo() {
        distanca1+=10;
        distanca2+=10;
        distanca3+=10;
        distanca4+=10;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jLabel6.setVisible(false);
         Thread animation= new Thread(new Runnable(){
            
           Random r=new Random();
            @Override
            public void run() {
                int x=50;                   
                
                while(distanca1<=GJATESIA_E_PISTES ){
                   jLabel1.setLocation(distanca1, x);
                    
                    try{
                        Thread.sleep(r.nextInt(2000));
                    }catch(Exception e){
                        
                    }
                    vrapo();
                   if(distanca1==GJATESIA_E_PISTES){
                        jLabel1.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                        jLabel6.setVisible(true);
                        jLabel6.setText("Fitoi: "+jLabel1.getText());
                    }
                }
                 
            }
            
        });
         Thread animation2= new Thread(new Runnable(){
            
           Random r=new Random();
            @Override
            public void run() {
                
                int y=190;                    
                
                while(distanca2<=GJATESIA_E_PISTES ){
                    jLabel2.setLocation(distanca2,y);
                    
                    try{
                        Thread.sleep(r.nextInt(2000));
                    }catch(Exception e){
                        
                    }
                    vrapo();
                    if(distanca2==GJATESIA_E_PISTES){
                        jLabel1.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                        jLabel6.setVisible(true);
                        jLabel6.setText("Fitoi: "+jLabel2.getText());
                    }
                }
               
            }
            
        });
         
         Thread animation3= new Thread(new Runnable(){
            
           Random r=new Random();
            @Override
            public void run() {
                int y=360;                    
                
                while(distanca3<=GJATESIA_E_PISTES ){
                    jLabel3.setLocation(distanca3,y);
                    
                    try{
                        Thread.sleep(r.nextInt(2000));
                    }catch(Exception e){
                        
                    }
                    vrapo();
                    if(distanca3==GJATESIA_E_PISTES){
                        jLabel1.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                        jLabel6.setVisible(true);
                        jLabel6.setText("Fitoi: "+jLabel3.getText());
                    }
                }
            }
            
        });
         Thread animation4= new Thread(new Runnable(){
            
           Random r=new Random();
            @Override
            public void run() {
                int y=500;                   
                
                while(distanca4<=GJATESIA_E_PISTES ){
                    jLabel4.setLocation(distanca4,y);
                    
                    try{
                        Thread.sleep(r.nextInt(2000));
                    }catch(Exception e){
                        
                    }
                    vrapo();
                    if(distanca4==GJATESIA_E_PISTES){
                        jLabel1.setVisible(false);
                        jLabel2.setVisible(false);
                        jLabel3.setVisible(false);
                        jLabel4.setVisible(false);
                        jLabel6.setVisible(true);
                        jLabel6.setText("Fitoi: "+jLabel4.getText());
                    }
                }
            }
            
        });
         
        animation.start();
        animation2.start();
        animation3.start();
        animation4.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
